name: CI
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  test_build:
    uses: trfore/docker-image/.github/workflows/test_systemd.yml@main # remote repo
